name: ESLint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint . --format json --output-file eslint-report.json
        continue-on-error: true

      - name: Upload ESLint report
        uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: eslint-report.json

      - name: Check ESLint results
        id: eslint-check
        run: |
          errors=$(jq '.length' eslint-report.json)
          if [ $errors -gt 0 ]; then
            echo "eslint_failed=true" >> $GITHUB_OUTPUT
          fi

      - name: Notify on ESLint errors
        if: steps.eslint-check.outputs.eslint_failed == 'true'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: ESLint found errors in the code. Please check the report.
          author_name: ESLint Check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
